.TH music123 1 "July 24, 2002"

.SH NAME
music123 \- plays various sound files (usually including MP3, Ogg and Wav).

.SH SYNOPSIS
.B music123
[
.B -hqrvz
]
.I file
.B ...

.SH DESCRIPTION
.B music123
is a shell around various command line programs to play music files.
It will descend directories trees with \-r, and randomize file lists
with \-z. The programs used and the options given them are listed
in /etc/music123rc or ~/.music123rc.

.SH OPTIONS
.IP -h
Show command help and exit;
.IP -q
Quiet mode.  No messages are displayed.
.IP -r
Recurse into directories, instead of ignoring them.
.IP -v
Display version information and exit.
.IP -z
Play files in random order.
.IP -Z
Play the files randomly and endlessly.
.IP -l
Loop. \-z \-l differs from \-Z in that \-z \-l will randomize, play
through the song list (without repetition) in random order once,
and repeat the songs in that order over and over; \-Z will randomly
play the songs, without any order, and will possibly play a song
right after itself.
.IP -D
Set music123 not to delay between songs. (May make music123 harder to
kill).
.IP -d
Customize the time music123 delays between songs. \-d takes one argument,
expressed in seconds, which may have a fractional part.
.IP -@
Play the files listed in the mandatory argument of -@. Other files can be
added on the command line, and this option can be given several times.
Note that music123 doesn't yet play URLs.
.IP --
End option list.

.SH EXAMPLES

Play three songs:
.RS
.B music123 test1.ogg test2.mp3 test3.wav
.RE
.PP

Play a couple of directories and other songs at random:
.RS
.B music123 -z -r Rock/ test1.ogg Pop/ test4.wav
.RE
.PP

.SH FILES

.TP
/etc/music123rc
Describes which programs
.B music123
uses, which files types it supports,
and which options it passes those programs.

.TP
~/.music123rc
Per-user config file to override the system wide settings.
.PP

.SH AUTHORS

.TP
Authors:
.br
David Starner <dvdeug@debian.org>
.br
